import { Campaign, Asset, Submission, User, CampaignWithAssets } from "@/types"

export const mockUsers: User[] = [
  {
    id: "1",
    email: "maya@example.com",
    displayName: "Maya Chen",
    avatarUrl: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=64&h=64&fit=crop&crop=face",
    emailVerified: true,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-12-01"),
  },
  {
    id: "2",
    email: "david@example.com",
    displayName: "David Rodriguez",
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=64&h=64&fit=crop&crop=face",
    emailVerified: true,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-12-01"),
  },
]

export const mockAssets: Asset[] = [
  {
    id: "asset-1",
    filename: "hero-character.png",
    originalFilename: "hero-character.png",
    url: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=200&h=200&fit=crop",
    category: "characters",
    tags: ["hero", "character", "anime"],
    metadata: { width: 200, height: 200, fileSize: 45000, mimeType: "image/png" },
    ipKitId: "kit-1",
    createdAt: new Date("2024-11-15"),
  },
  {
    id: "asset-2",
    filename: "fantasy-background.jpg",
    originalFilename: "fantasy-background.jpg",
    url: "https://images.unsplash.com/photo-1518709268805-4e9042af2176?w=400&h=300&fit=crop",
    category: "backgrounds",
    tags: ["fantasy", "background", "nature"],
    metadata: { width: 400, height: 300, fileSize: 85000, mimeType: "image/jpeg" },
    ipKitId: "kit-1",
    createdAt: new Date("2024-11-15"),
  },
  {
    id: "asset-3",
    filename: "studio-logo.svg",
    originalFilename: "studio-logo.svg",
    url: "https://images.unsplash.com/photo-1611224923853-80b023f02d71?w=150&h=150&fit=crop",
    category: "logos",
    tags: ["logo", "brand"],
    metadata: { width: 150, height: 150, fileSize: 12000, mimeType: "image/svg+xml" },
    ipKitId: "kit-1",
    createdAt: new Date("2024-11-15"),
  },
]

export const mockCampaigns: CampaignWithAssets[] = [
  {
    id: "1",
    title: "Anime Heroes Collection",
    description: "Create amazing artwork using our official anime character assets. Express your creativity while staying true to our brand aesthetic.",
    guidelines: "Use provided characters in creative compositions. No violent themes. Maintain character proportions and color schemes. Family-friendly content only.",
    brandId: "brand-1",
    ipKitId: "kit-1",
    status: "active",
    endDate: new Date("2025-08-01"),
    createdBy: "2",
    createdAt: new Date("2024-11-01"),
    updatedAt: new Date("2024-11-15"),
    assets: mockAssets,
    brand: {
      id: "brand-1",
      name: "Studio Ghibli",
      ownerId: "2",
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    submissionCount: 24,
    featured: true,
  },
  {
    id: "2",
    title: "Cyberpunk City Designs",
    description: "Design futuristic cityscapes using our sci-fi asset collection. Perfect for digital artists interested in cyberpunk aesthetics.",
    guidelines: "Focus on neon lighting and futuristic architecture. Use dark color palette with bright accent colors. Include our brand elements subtly.",
    brandId: "brand-2",
    ipKitId: "kit-2",
    status: "active",
    endDate: new Date("2025-07-15"),
    createdBy: "3",
    createdAt: new Date("2024-10-15"),
    updatedAt: new Date("2024-11-01"),
    assets: [],
    brand: {
      id: "brand-2",
      name: "NeonCorp Studios",
      ownerId: "3",
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    submissionCount: 12,
    featured: true,
  },
  {
    id: "3",
    title: "Fantasy Realm Adventure",
    description: "Create magical scenes with our fantasy character and environment assets. Bring mystical worlds to life.",
    guidelines: "Emphasize magical elements and vibrant colors. Characters should appear heroic and inspiring. Suitable for all ages.",
    brandId: "brand-3",
    ipKitId: "kit-3",
    status: "draft",
    endDate: new Date("2025-09-01"),
    createdBy: "4",
    createdAt: new Date("2024-11-20"),
    updatedAt: new Date("2024-11-20"),
    assets: [],
    brand: {
      id: "brand-3",
      name: "Mystic Games",
      ownerId: "4",
      createdAt: new Date("2024-01-01"),
      updatedAt: new Date("2024-01-01"),
    },
    submissionCount: 0,
  },
]

export const mockSubmissions: Submission[] = [
  {
    id: "sub-1",
    campaignId: "1",
    creatorId: "1",
    title: "Heroes Unite",
    description: "A dynamic composition featuring the main character in an action pose with mystical background elements.",
    artworkUrl: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=400&h=300&fit=crop",
    tags: ["hero", "action", "dynamic"],
    status: "approved",
    feedback: "Excellent composition and use of brand assets. Great attention to character details!",
    isPublic: true,
    viewCount: 156,
    likeCount: 23,
    createdAt: new Date("2024-11-25"),
    updatedAt: new Date("2024-11-26"),
  },
  {
    id: "sub-2",
    campaignId: "1",
    creatorId: "1",
    title: "Peaceful Moment",
    description: "A serene scene showcasing the character in a calm, contemplative setting.",
    artworkUrl: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop",
    tags: ["peaceful", "serene", "character"],
    status: "pending",
    isPublic: false,
    viewCount: 0,
    likeCount: 0,
    createdAt: new Date("2024-11-28"),
    updatedAt: new Date("2024-11-28"),
  },
]